### ISSUE TITLE
Cannot access /feed 

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_rss#6]
In my usual [subdir situation](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url) the RSS access does not work. The URL `/customSubDir/p/padname/feed` returns an error.

I already tried changing [this line](https://github.com/JohnMcLear/ep_rss/blob/master/index.js#L40) to 
```js
args.app.get('/p/:pad/:rev?/feed', function(req, res) {
```
but it did not work either.

**Comment by JohnMcLear** [comment]
not sure, the rewrite should be working and allow it to access it.  Try access it without your rewrite (ie hit it direct)

**Comment by rugk** [comment]
Can I somehow do this directly on the server? With `curl`?

**Comment by JohnMcLear** [comment]
/me shrugs -- It's your server dude!

**Comment by rugk** [comment]
Oh, nice what slang we finally got here. 
I'll test it out...

**Comment by rugk** [comment]
So the result is: Accessing it directly works.

So it must (again) be an issue with the sub-directory somehow...

**Comment by JohnMcLear** [comment]
I would expect your proxy rewrite is not properly configured as the URLs aren't be being passed back correctly.
